// <auto-generated />
using System;
using Mc2.CrudTest.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mc2.CrudTest.Persistence.Migrations
{
    [DbContext(typeof(Mc2Context))]
    partial class Mc2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mc2.CrudTest.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Mc2_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Firstname", "Lastname", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankAccountNumber = "123456",
                            DateOfBirth = new DateTime(1981, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hamidnch2007@gmail.com",
                            Firstname = "Hamid",
                            Lastname = "NCH",
                            PhoneNumber = "09124820700"
                        },
                        new
                        {
                            Id = 2,
                            BankAccountNumber = "3251388",
                            DateOfBirth = new DateTime(2001, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "RazaviAli@gmail.com",
                            Firstname = "Ali",
                            Lastname = "Razavi",
                            PhoneNumber = "09123526532"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
