// <auto-generated />
using System;
using Mc2.CrudTest.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mc2.CrudTest.Persistence.Migrations
{
    [DbContext(typeof(Mc2Context))]
    partial class Mc2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mc2.CrudTest.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("PhoneNumber")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Mc2_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Firstname", "Lastname", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3d91ba2-e1a0-4134-badf-d5fb304fd990"),
                            BankAccountNumber = "123456",
                            DateOfBirth = new DateTime(1981, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hamidnch2007@gmail.com",
                            Firstname = "Hamid",
                            Lastname = "NCH",
                            PhoneNumber = 9124820700m
                        },
                        new
                        {
                            Id = new Guid("a43371d0-00a4-4320-9e1d-f19ea81fc651"),
                            BankAccountNumber = "3251388",
                            DateOfBirth = new DateTime(2001, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "RazaviAli@gmail.com",
                            Firstname = "Ali",
                            Lastname = "Razavi",
                            PhoneNumber = 9123526532m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
